### ISSUE TITLE
Alwa's Awakening - The 8-Bit Edition (World) (Demo) (Aftermarket) (Unl).nes messed up graphics

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#93] opened 2024-06-23 10:04 UTC

**Comment by jsgroth** [comment] 2024-06-24 16:17
This is caused by the UxROM mapper code assuming that the cartridge will never have any PRG RAM (hence the "mapper test fail" screen at boot). That assumption holds for every UxROM game released in the 80s and 90s as far as I know, but it's incorrect for Alwa's Awakening because it uses a UxROM-compatible mapper and has 8KB of PRG RAM in the cartridge.

Allowing UxROM games to map PRG RAM fixes this:
![alwa](https://github.com/jsgroth/jgenesis/assets/1137683/d1052b67-8eb3-4d64-b654-4808f2b8c451)

**Closed** 2024-09-16 21:52 UTC
Labels: bug, fixed-next-release, nes
